#ifndef __ORDER_H__
#define __ORDER_H__

#define MAX_MONSTER 50

#define ZORDER_BACKGROUND 0
#define ZORDER_UNIT 1
#define ZORDER_INFORBOARD 2
#define ZORDER_INTERfACE 3

#define TAG_BACKGROUND 1000
#define TAG_UNIT 1001
#define TAG_INFORBOARD 1002
#define TAG_INTERFACE 1003

#define ZORDER_RANGE 1
#define ZORDER_MONSTER 2
#define ZORDER_CHARACTER 3
#define ZORDER_MONSTER_DEATH 4
#define ZORDER_BULLET 10

#define TAG_RANGE 2001
#define TAG_MONSTER 2002
#define TAG_CHARACTER 2003

#endif